name: Update GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create folder
        run: mkdir -p dist

      - name: Download SVG
        run: |
          curl -L -o dist/top-langs.svg \
          "https://github-readme-stats.vercel.app/api/top-langs/?username=BeatrizLorenaCosta&theme=github"

      - name: Commit changes
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add dist/top-langs.svg
          git commit -m "Update stats" || echo "No changes"
          git push
